//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Lectures = new HashSet<Lecture>();
            this.StudentComments = new HashSet<StudentComment>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int CourseId { get; set; }
        public string Name { get; set; }
        public System.DateTime PublishDate { get; set; }
        public Nullable<double> Estimation { get; set; }
        public Nullable<int> EstimationCount { get; set; }
        public int CategoryId { get; set; }
        public int TeacherId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Lecture> Lectures { get; set; }
        public virtual ICollection<StudentComment> StudentComments { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
