//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentComments = new HashSet<StudentComment>();
            this.Subscriptions = new HashSet<Subscription>();
            this.StudentConnections = new HashSet<StudentConnection>();
        }
    
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime RegDate { get; set; }
        public int Activation { get; set; }
    
        public virtual ICollection<StudentComment> StudentComments { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<StudentConnection> StudentConnections { get; set; }
    }
}
