//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherComment
    {
        public int TeacherCommentId { get; set; }
        public int StudentCommentId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string Text { get; set; }
    
        public virtual StudentComment StudentComment { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
